# Generated by Django 2.2 on 2020-11-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='thumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('title', models.TextField(null=True)),
                ('content', models.TextField(null=True)),
                ('genre', models.CharField(choices=[('action', 'ACTION'), ('comedy', 'COMEDY'), ('thriller', 'THRILLER'), ('motivational', 'MOTIVATIONAL')], max_length=40)),
                ('language', models.TextField(null=True)),
                ('avg_rate', models.IntegerField(default=0, null=True)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
