# Generated by Django 2.2 on 2020-11-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thumbnails', '0003_auto_20201105_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
