# Generated by Django 2.2 on 2020-11-02 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thumbnails', '0004_auto_20201102_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbnail',
            name='title',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
