# Generated by Django 2.2 on 2020-11-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thumbnails', '0006_auto_20201106_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
