# Generated by Django 2.2 on 2020-11-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thumbnails', '0008_auto_20201106_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='language',
            field=models.CharField(choices=[('Tamil', 'TAMIL'), ('English', 'ENGLISH'), ('Telugu', 'TELUGU'), ('Hindi', 'HINDI'), ('Malayalam', 'MALAYALAM'), ('Urdhu', 'URDHU')], max_length=30, null=True),
        ),
    ]
