# Generated by Django 2.2 on 2020-11-02 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thumbnails', '0008_thumbnail_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thumbnail',
            name='genre',
        ),
    ]
