# Generated by Django 2.2 on 2020-11-08 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thumbnails', '0009_auto_20201106_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_rate', to='thumbnails.thumbnail'),
        ),
    ]
