# Generated by Django 2.2 on 2020-11-02 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thumbnails', '0011_auto_20201102_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
