# Generated by Django 2.2 on 2020-11-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thumbnails', '0012_auto_20201102_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbnail',
            name='rate',
            field=models.IntegerField(default=1),
        ),
    ]
