# Generated by Django 2.2 on 2020-11-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thumbnails', '0013_thumbnail_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbnail',
            name='avg_rate',
            field=models.FloatField(default=1),
        ),
    ]
