# Generated by Django 2.2 on 2020-11-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thumbnails', '0014_thumbnail_avg_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbnail',
            name='language',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
