# Generated by Django 2.2 on 2020-11-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thumbnails', '0015_thumbnail_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
