# Generated by Django 2.2 on 2020-11-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thumbnails', '0016_auto_20201102_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='avg_rate',
            field=models.FloatField(default=0.1),
        ),
    ]
