# Generated by Django 2.2 on 2020-11-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thumbnails', '0017_auto_20201102_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='avg_rate',
            field=models.FloatField(default=0.1, null=True),
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='rate',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
