# Generated by Django 2.2 on 2020-11-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thumbnails', '0018_auto_20201102_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='language',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
