# Generated by Django 2.2 on 2020-11-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thumbnails', '0019_auto_20201102_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='language',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='title',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
