# Generated by Django 2.2 on 2020-11-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thumbnails', '0021_auto_20201102_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbnail',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
