# Generated by Django 2.2 on 2020-11-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thumbnails', '0023_auto_20201102_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbnail',
            name='avg_rate',
            field=models.FloatField(null=True),
        ),
    ]
