# Generated by Django 2.2 on 2020-11-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thumbnails', '0025_auto_20201102_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='avg_rate',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
