# Generated by Django 2.2 on 2020-11-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thumbnails', '0026_auto_20201102_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='assets/image/'),
        ),
    ]
