# Generated by Django 2.2 on 2020-11-04 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thumbnails', '0031_auto_20201103_0624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thumbnail',
            name='user',
        ),
        migrations.AddField(
            model_name='thumbnail',
            name='rated_user',
            field=models.IntegerField(null=True),
        ),
    ]
