# Generated by Django 2.2 on 2020-11-04 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thumbnails', '0032_auto_20201104_0409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thumbnail',
            name='rated_user',
        ),
    ]
