# Generated by Django 2.2 on 2020-11-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thumbnails', '0033_remove_thumbnail_rated_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='language',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
